/**
 * Plan Type Definitions
 * 
 * Defines the structure of AI-generated UI plans.
 * Plans are created by the planner agent before being converted to actual UI trees.
 * 
 * @module types/plan
 */

/**
 * Specification for a single component in the plan.
 * 
 * More detailed than UINode, includes AI reasoning and forms a tree structure.
 * Used during the planning phase before final UI generation.
 * 
 * @property type - Component type name
 * @property props - Component properties
 * @property children - Nested component specifications
 * @property reasoning - AI explanation for why this component was chosen
 */
export type ComponentSpec = {
  type: string;
  props: Record<string, any>;
  children?: ComponentSpec[];
  reasoning?: string; // Why this component was chosen
};

/**
 * Complete UI plan generated by the planner agent.
 * 
 * Includes the component tree, metadata, and reasoning.
 * This structured approach allows for better debugging and user feedback.
 * 
 * @property mode - Whether creating new UI or modifying existing
 * @property intent - Original user request
 * @property root - Root component specification (tree structure)
 * @property description - High-level summary of what was planned
 * @property changes - Diff information for modify mode (optional)
 * @property constraints - System constraints applied during planning
 * 
 * @example
 * ```typescript
 * const plan: Plan = {
 *   mode: "create",
 *   intent: "Create a dashboard",
 *   root: {
 *     type: "Navbar",
 *     props: { title: "Dashboard" },
 *     children: [{ type: "Card", props: {}, children: [] }],
 *     reasoning: "Navbar provides top-level navigation"
 *   },
 *   description: "Dashboard with navigation",
 *   constraints: {
 *     allowedComponents: ["Navbar", "Card"],
 *     maxDepth: 5
 *   }
 * };
 * ```
 */
export type Plan = {
  mode: "create" | "modify";
  intent: string; // Original user intent
  root: ComponentSpec;
  description: string; // High-level description of changes
  changes?: {
    // For modify mode
    added: string[]; // Component types added
    removed: string[]; // Component types removed
    modified: string[]; // Component types modified
  };
  constraints: {
    // Constraints applied
    allowedComponents: string[];
    maxDepth: number;
  };
};
